### ISSUE TITLE
打赏二维码如何加两个

### ISSUE THREAD

**Issue by liu-ziming** [ochukai/hexo-theme-ochuunn#7]
您好想问一下打赏二维码加两个怎么办，我重复了一行代码，不行诶

**Comment by ochukai** [comment]
```yaml
reward_images: 
- type: '微信'
  url: '/img/wechat.png'
# - type: '支付宝' 
#   url: '/img/wechat.png'
```
现在打赏的设置改成这样了~ (正在提交......)
